name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 0000  # 설정한 비밀번호
        ports:
          - 3306:3306  # 포트 매핑

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    # MySQL 클라이언트를 설치하는 과정 제거

    # 충분한 대기 시간을 추가하여 MySQL 서버가 준비되도록 함
    - name: Wait for MySQL to be ready
      run: sleep 30

    # MySQL 연결 확인
    - name: Check MySQL connection
      run: |
        mysql -h 127.0.0.1 -u root -p0000 -e "SHOW DATABASES;"  # 'mysql' 대신 '127.0.0.1' 사용

    - name: Check MySQL port 3306
      run: telnet localhost 3306

    - name: Grant execute permission for gradlew
      run: cd todo && chmod +x gradlew

    - name: Install dependencies
      run: cd todo && ./gradlew dependencies

    - name: Run tests
      working-directory: todo
      run: ./gradlew test
