name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 0000  # 설정한 비밀번호
        ports:
          - 3306:3306

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Install MySQL client
      run: sudo apt-get install mysql-client

    # MySQL 서버를 로컬에서 사용할 수 있도록 환경변수 설정
    - name: Setup MySQL
      uses: samin/mysql-action@v1
      with:
          mysql database: 'todo' 
          mysql user: 'root'
          mysql password: '0000'

    # MySQL 연결 확인
    - name: Check MySQL connection
      run: |
        sleep 30  # 충분한 대기 시간 추가
        mysql -h mysql -u root -p0000 -e "SHOW DATABASES;"  # 서비스 이름 mysql 사용

    - name: Check MySQL port 3306
      run: telnet localhost 3306

    - name: Grant execute permission for gradlew
      run: cd todo && chmod +x gradlew

    - name: Install dependencies
      run: cd todo && ./gradlew dependencies

    - name: Wait for MySQL to be ready
      run: sleep 10s

    - name: Run tests
      working-directory: todo
      run: ./gradlew test
